base_url = "https://aviralg.github.io/new-website"
title = "Aviral Goel"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]


navbar_items = [
  { url = "$BASE_URL/cv/cv.pdf", name = "CV" },
  { url = "$BASE_URL/publications", name = "Publications" },
	{ url = "$BASE_URL/posts", name = "Posts" },
	{ url = "$BASE_URL/docs", name = "Docs" },
	{ url = "$BASE_URL/tags", name = "Tags" },
	{ url = "$BASE_URL/categories", name = "Categories" },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Aviral Goel"
avatar = "images/aviral.jpg"

[extra.social]
location = "https://goo.gl/maps/7KerhccCRtxJnmPN7"
github = "aviralg"
linkedin = "aviralgoel"
twitter = "TheAviralGoel"
google_scholar = "_cEObskAAAAJ"
orcid = "0000-0002-0814-5015"
email = "aviral@aviral.io"
cv = "cv/cv.pdf"
dblp = "209/9875"

[extra.analytics]
google = "UA-176984489-2"

[extra.commenting]
hyvor = "1967"

[extra.mapbox]
access_token = "pk.eyJ1IjoicmF0YW5zaHJlc2h0aGEiLCJhIjoiY2tla2s2NmM3MDd0ZzJzbXFtc3Y2YmU0NyJ9.0RhUnJPKbxHWw3xGPnnBlA"
